# Generated by Django 3.2.12 on 2022-02-18 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='items',
            old_name='quen',
            new_name='quan',
        ),
        migrations.AddField(
            model_name='items',
            name='active',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
