# Generated by Django 3.2.12 on 2022-02-18 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_auto_20220218_1346'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='active',
            field=models.BooleanField(blank=True),
        ),
    ]
