# Generated by Django 3.2.12 on 2022-02-18 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0003_alter_items_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='active',
        ),
    ]
