# Generated by Django 3.2.12 on 2022-02-18 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0004_remove_items_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='active',
            field=models.BooleanField(blank=True, default=0),
            preserve_default=False,
        ),
    ]
