# Generated by Django 3.2.12 on 2022-02-18 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0005_items_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
